changed 'failed' message to bold red

diff --git a/c/makefile b/c/makefile
--- a/c/makefile
+++ b/c/makefile
@@ -9,17 +9,17 @@ clean:
 	rm -f ${ALL_TEST_EXE}
 
 test:	all
-	@for test in ${ALL_TEST_EXE};  \
-		do                           \
-			echo testing $${test} ;    \
-			./$${test} ;               \
-		  if [ $$? -ne 0 ] ;         \
-		  then                       \
-		    echo failed ;            \
-		  else                       \
-		    echo passed ;            \
-		  fi ;                       \
-		  echo ;                     \
+	@for test in ${ALL_TEST_EXE};              \
+		do                                       \
+			echo testing $${test} ;                \
+			./$${test} ;                           \
+		  if [ $$? -ne 0 ] ;                     \
+		  then                                   \
+		    /bin/echo -e "\e[01;31mfailed\e[m" ; \
+		  else                                   \
+		    echo passed ;                        \
+		  fi ;                                   \
+		  echo ;                                 \
 		done 
 
 %_test:	%_test.c %.c %.h
