created makefile for two files that need special compilation

diff --git a/c/containers/makefile b/c/containers/makefile
--- a/c/containers/makefile
+++ b/c/containers/makefile
@@ -1,9 +1,29 @@
-CFLAGS		:= -Wall -pedantic -std=c11
+ALL_TEST_SRC 	:= $(shell find . -name '*_testspecial.c')
+ALL_TEST_EXE	:= ${ALL_TEST_SRC:.c=}
 
-special: heap_test_special
+CFLAGS := -g -Wall -pedantic -std=c11
 
-heap_test_special: heap_test_special.c heap.c dynamic_array.c heap.h dynamic_array.h
-	clang ${CFLAGS} -o $@ heap_test_special.c dynamic_array.c
+special: heap_testspecial dynamic_array_testspecial
+
+test:	special
+	@for test in ${ALL_TEST_EXE} ;            \
+	  do                                      \
+	    echo testing $${test} ;               \
+	    ./$${test} ;                          \
+	    if [ $$? -ne 0 ] ;                    \
+	    then                                  \
+	      /bin/echo -e "\e[01;31mfailed\e[m" ;\
+	    else                                  \
+	      echo passed ;                       \
+	    fi ;                                  \
+	    echo ;                                \
+	  done 
+
+heap_testspecial: heap_testspecial.c heap.c dynamic_array.c heap.h dynamic_array.h
+	clang ${CFLAGS} -o $@ heap_testspecial.c dynamic_array.c -lpthread
+
+dynamic_array_testspecial: dynamic_array_testspecial.c dynamic_array.c dynamic_array.h
+	clang ${CFLAGS} -o $@ dynamic_array_testspecial.c -lpthread
 
 clean:
-	rm -f heap_test_special
+	rm -f heap_testspecial dynamic_array_testspecial
